from building import *

cwd     = GetCurrentDir()
src     = []
CPPDEFINES = []
CPPPATH = []

#include
CPPPATH += [cwd + r'/include/']
CPPPATH += [cwd + r'/../include/isp/cv181x/']
CPPPATH += [cwd + r'/../cvi_mw_isp/include/']
CPPPATH += [cwd + r'/../cvi_mw_isp/src/']
CPPPATH += [cwd + r'/../cvi_mw_isp_algo/include/']


print(CPPPATH)
# src
src += Glob(cwd + r'/src/*.c')
#CPPDEFINES += ['-D__CV181X__']
print(src)
cvi_mw_isp_ae = DefineGroup('cvi_mw_isp_ae', src, depend = [''], CPPDEFINES = CPPDEFINES, CPPPATH = CPPPATH)

Return('cvi_mw_isp_ae')