import os
from building import *

cwd = GetCurrentDir()
objs = []
obj_path = []
if GetDepend('BSP_USING_CVIRUNTIME'):
    # Traverse all entries in the current directory
    for entry in os.listdir(cwd):
        entry_path = os.path.join(cwd, entry)
        # Check whther entry is directory
        if os.path.isdir(entry_path):
            # Check whether contain SConscript file
            sconscript = os.path.join(entry_path, 'SConscript')
            if os.path.isfile(sconscript):
                # Execute SConscript in subdirectory
                objs.extend(SConscript(sconscript))
                obj_path.extend([sconscript])
Return('objs')