from building import *

cwd     = GetCurrentDir()
src     = []
CPPDEFINES = []
CPPPATH = []

#include
CPPPATH += [cwd + r'/include/']



print(CPPPATH)
# src
src += Glob(cwd + r'/src/*.c')

print(src)
cvi_mw_isp_af = DefineGroup('cvi_mw_isp_af', src, depend = [''], CPPDEFINES = CPPDEFINES, CPPPATH = CPPPATH)

Return('cvi_mw_isp_af')