import os
import sys
import rtconfig

from rtconfig import RTT_ROOT

sys.path = sys.path + [os.path.join(RTT_ROOT, 'tools')]
from building import *

TARGET = 'rtthread.' + rtconfig.TARGET_EXT

DefaultEnvironment(tools=[])
env = Environment(tools = ['mingw'],
    AS = rtconfig.AS, ASFLAGS = rtconfig.AFLAGS,
    CC = rtconfig.CC, CCFLAGS = rtconfig.CFLAGS,
    CXX = rtconfig.CXX, CXXFLAGS = rtconfig.CXXFLAGS,
    AR = rtconfig.AR, ARFLAGS = '-rc',
    LINK = rtconfig.LINK, LINKFLAGS = rtconfig.LFLAGS)
env.PrependENVPath('PATH', rtconfig.EXEC_PATH)
env['ASCOM'] = env['ASPPCOM']

Export('RTT_ROOT')
Export('rtconfig')

SDK_ROOT = os.path.abspath('./')

drivers_path_prefix = os.path.dirname(SDK_ROOT) + '/cvi_common/drivers'
cpu_path_prefix = os.path.dirname(SDK_ROOT) + '/cv18xx_boot/cpu/risc-v'
utils_path_prefix = os.path.dirname(SDK_ROOT) + '/cv18xx_boot/utils/partition/'
sys_path_prefix = os.path.dirname(SDK_ROOT) + '/cvi_common/sys'

# prepare building environment
objs = PrepareBuilding(env, RTT_ROOT, has_libcpu = False)

# include libraries
objs.extend(SConscript(drivers_path_prefix + '/SConscript', variant_dir='build/cvi_common/drivers', duplicate=0))
objs.extend(SConscript(utils_path_prefix + '/SConscript', variant_dir='build/cv18xx_boot/utils', duplicate=0))
objs.extend(SConscript(sys_path_prefix + '/SConscript', variant_dir='build/cvi_common/sys', duplicate=0))

stack_size = 4096

stack_lds = open('link_stacksize.lds', 'w')
if GetDepend('__STACKSIZE__'):
    stack_size = GetDepend('__STACKSIZE__')
stack_lds.write('__STACKSIZE__ = %d;\n' % stack_size)
stack_lds.close()

# make a building
DoBuilding(TARGET, objs)
