from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd]
CPPPATH += [cwd + r'../../cvi_common/cvi_hal']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
